# **Automatidata project**
**Course 1 - Foundations of Data Science**

Welcome to the Automatidata Project!

You have just started as a data professional in a fictional data consulting firm, Automatidata. Their client, the New York City Taxi and Limousine Commission (New York City TLC), has hired the Automatidata team for its reputation in helping their clients develop data-based solutions.

The team is still in the early stages of the project. You have received notice that New York City TLC has given the Automatidata team access to their data. To get clear insights, New York TLC's data must be inspected, key variables identified, and the dataset prepared for analysis.

A notebook was structured and prepared to help you in this project. Please complete the following questions.

# Course 1 End-of-course project: Inspect and analyze data

In this activity, you will examine data provided and prepare it for analysis.  This activity will help ensure the information is,

1.   Ready to answer questions and yield insights

2.   Ready for visualizations

3.   Ready for future hypothesis testing and statistical methods
<br/>    

**The purpose** of this project is to investigate and understand the data provided.
  
**The goal** is to use a dataframe contructed within Python, perform a cursory inspection of the provided dataset, and inform team members of your findings. 
<br/>  
*This activity has three parts:*

**Part 1:** Understand the situation 
* Prepare to understand and organize the provided taxi cab dataset and information.

**Part 2:** Understand the data

* Create a pandas dataframe for data learning, future exploratory data analysis (EDA), and statistical activities.

* Compile summary information about the data to inform next steps.

**Part 3:** Understand the variables

* Use insights from your examination of the summary data to guide deeper investigation into specific variables.


<br/> 
Follow the instructions and answer the following questions to complete the activity. Then, you will complete an Executive Summary using the questions listed on the PACE Strategy Document.

Be sure to complete this activity before moving on. The next course item will provide you with a completed exemplar to compare to your own work.

# **Identify data types and relevant variables using Python**

<img src="images/Pace.png" width="100" height="100" align=left>

# **PACE stages**

Throughout these project notebooks, you'll see references to the problem-solving framework PACE. The following notebook components are labeled with the respective PACE stage: Plan, Analyze, Construct, and Execute.

<img src="images/Plan.png" width="100" height="100" align=left>


## PACE: **Plan**

Consider the questions in your PACE Strategy Document and those below to craft your response:

### **Task 1. Understand the situation**

*   How can you best prepare to understand and organize the provided taxi cab information?

==> ENTER YOUR RESPONSE HERE

<img src="images/Analyze.png" width="100" height="100" align=left>

## PACE: **Analyze**

Consider the questions in your PACE Strategy Document to reflect on the Analyze stage.

### **Task 2a. Build dataframe**

Create a pandas dataframe for data learning, and future exploratory data analysis (EDA) and statistical activities.

**Code the following,**

*   import pandas as `pd`. pandas is used for buidling dataframes.

*   import numpy as `np`. numpy is imported with pandas

*   `df = pd.read_csv('Datasets\NYC taxi data.csv')`

**Note:** pair the data object name `df` with pandas functions to manipulate data, such as `df.groupby()`.

**Note:** As shown in this cell, the dataset has been automatically loaded in for you. You do not need to download the .csv file, or provide more code, in order to access the dataset and proceed with this lab. Please continue with this activity by completing the following instructions.

In [2]:
#Import libraries and packages listed above
### YOUR CODE HERE ###
import pandas as pd
# Load dataset into dataframe
df = pd.read_csv('2017_Yellow_Taxi_Trip_Data.csv')
print("done")

done

### **Task 2b. Understand the data - Inspect the data**

View and inspect summary information about the dataframe by coding the following:

1. `df.head(10)`
2. `df.info()`
3. `df.describe()`

Consider the following two questions:

**Question 1:** When reviewing the `df.info()` output, what do you notice about the different variables? Are there any null values? Are all of the variables numeric? Does anything else stand out?

**Question 2:** When reviewing the `df.describe()` output, what do you notice about the distributions of each variable? Are there any questionable values?

==> ENTER YOUR RESPONSE TO QUESTIONS 1 & 2 HERE

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Unnamed: 0             100 non-null    int64
 1   VendorID               100 non-null    int64
 2   tpep_pickup_datetime   100 non-null    str
 3   tpep_dropoff_datetime  100 non-null    str
 4   passenger_count        100 non-null    int64
 5   trip_distance          100 non-null    float64
 6   RatecodeID             100 non-null    int64
 7   store_and_fwd_flag     100 non-null    str
 8   PULocationID           100 non-null    int64
 9   DOLocationID           100 non-null    int64
 10  payment_type           100 non-null    int64
 11  fare_amount            100 non-null    float64
 12  extra                  100 non-null    float64
 13  mta_tax                100 non-null    float64
 14  tip_amount             100 non-null    float64
 15  tolls_amount           100 non-null    float64
 16  improvement_surcharge  100 non-null    float64
 17  total_amount           100 non-null    float64
dtypes: float64(8), int64(7), str(3)
memory usage: 14.2 KB

In [4]:
df.describe()

,Unnamed: 0,VendorID,passenger_count,trip_distance,RatecodeID,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
count,1.000000e+02,100.000000,100.00000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.0,100.000000
mean,5.331287e+07,1.620000,1.79000,3.348300,1.070000,164.010000,161.490000,1.280000,14.152500,0.315000,0.490000,2.352600,0.390800,0.3,18.000900
std,3.378051e+07,0.487832,1.45154,4.458955,0.455161,69.937562,74.169271,0.451261,12.854759,0.373727,0.070353,3.100865,2.121784,0.0,17.122142
min,1.361166e+06,1.000000,1.00000,0.220000,1.000000,4.000000,23.000000,1.000000,3.500000,0.000000,0.000000,0.000000,0.000000,0.3,5.160000
25%,2.158422e+07,1.000000,1.00000,1.015000,1.000000,122.750000,100.000000,1.000000,6.500000,0.000000,0.500000,0.000000,0.000000,0.3,8.757500
50%,5.084474e+07,2.000000,1.00000,1.785000,1.000000,162.500000,161.000000,1.000000,9.750000,0.000000,0.500000,1.645000,0.000000,0.3,12.850000
75%,8.402188e+07,2.000000,2.00000,3.025000,1.000000,236.000000,234.500000,2.000000,16.125000,0.500000,0.500000,2.850000,0.000000,0.3,20.200000
max,1.130747e+08,2.000000,6.00000,30.830000,5.000000,263.000000,265.000000,2.000000,80.000000,1.000000,0.500000,18.560000,16.260000,0.3,111.380000

In [5]:
df.head()

,Unnamed: 0,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
0,24870114,2,03/25/2017 8:55:43 AM,03/25/2017 9:09:47 AM,6,3.34,1,N,100,231,1,13.0,0.0,0.5,2.76,0.0,0.3,16.56
1,35634249,1,04/11/2017 2:53:28 PM,04/11/2017 3:19:58 PM,1,1.80,1,N,186,43,1,16.0,0.0,0.5,4.00,0.0,0.3,20.80
2,106203690,1,12/15/2017 7:26:56 AM,12/15/2017 7:34:08 AM,1,1.00,1,N,262,236,1,6.5,0.0,0.5,1.45,0.0,0.3,8.75
3,38942136,2,05/07/2017 1:17:59 PM,05/07/2017 1:48:14 PM,1,3.70,1,N,188,97,1,20.5,0.0,0.5,6.39,0.0,0.3,27.69
4,30841670,2,04/15/2017 11:32:20 PM,04/15/2017 11:49:03 PM,1,4.37,1,N,4,112,2,16.5,0.5,0.5,0.00,0.0,0.3,17.80

### **Task 2c. Understand the data - Investigate the variables**

Sort and interpret the data table for two variables:`trip_distance` and `total_amount`.

**Answer the following three questions:**

**Question 1:** Sort your first variable (`trip_distance`) from maximum to minimum value, do the values seem normal?

**Question 2:** Sort by your second variable (`total_amount`), are any values unusual?

**Question 3:** Are the resulting rows similar for both sorts? Why or why not?

==> ENTER YOUR RESPONSES TO QUESTION 1-3 HERE

In [6]:
# ==> ENTER YOUR CODE HERE

df.sort_values(by='trip_distance').head(20)

,Unnamed: 0,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
63,83622942,2,10/05/2017 9:39:28 AM,10/05/2017 9:42:32 AM,6,0.22,3,N,48,48,2,21.5,0.0,0.0,0.00,0.0,0.3,21.80
60,34663272,2,04/26/2017 6:08:41 PM,04/26/2017 6:11:08 PM,5,0.38,1,N,236,236,1,4.0,1.0,0.5,1.16,0.0,0.3,6.96
38,10421657,1,02/12/2017 6:45:41 PM,02/12/2017 6:48:58 PM,4,0.40,1,N,142,143,1,4.0,0.0,0.5,0.72,0.0,0.3,5.52
85,74722231,1,09/06/2017 11:37:10 AM,09/06/2017 11:40:44 AM,1,0.40,1,N,140,140,2,4.5,0.0,0.5,0.00,0.0,0.3,5.30
49,34839590,2,04/27/2017 7:26:57 AM,04/27/2017 7:28:21 AM,1,0.42,1,N,234,107,1,3.5,0.0,0.5,0.86,0.0,0.3,5.16
22,113074702,2,01/06/2017 8:12:07 PM,01/06/2017 8:18:37 PM,1,0.52,1,N,90,249,1,5.5,0.5,0.5,1.00,0.0,0.3,7.80
44,11969477,2,02/15/2017 5:30:24 PM,02/15/2017 5:35:24 PM,1,0.59,1,N,249,113,1,5.0,1.0,0.5,1.36,0.0,0.3,8.16
36,14770087,1,02/24/2017 11:24:50 AM,02/24/2017 11:29:18 AM,1,0.60,1,N,142,142,2,5.0,0.0,0.5,0.00,0.0,0.3,5.80
18,35388828,2,04/10/2017 6:12:58 PM,04/10/2017 6:17:39 PM,2,0.63,1,N,263,262,2,5.0,1.0,0.5,0.00,0.0,0.3,6.80
64,21974063,1,03/17/2017 9:17:05 AM,03/17/2017 9:21:34 AM,1,0.70,1,N,237,236,1,5.0,0.0,0.5,1.15,0.0,0.3,6.95
65,110794327,2,12/31/2017 1:03:12 PM,12/31/2017 1:06:52 PM,6,0.71,1,N,161,229,2,4.5,0.0,0.5,0.00,0.0,0.3,5.30
58,22352969,2,03/18/2017 12:12:18 PM,03/18/2017 12:20:32 PM,1,0.78,1,N,230,50,2,7.0,0.0,0.5,0.00,0.0,0.3,7.80
74,36762559,2,05/01/2017 9:42:27 AM,05/01/2017 9:47:29 AM,1,0.78,1,N,13,231,1,5.0,0.0,0.5,1.00,0.0,0.3,6.80
53,25497357,2,03/28/2017 7:10:03 PM,03/28/2017 7:13:20 PM,1,0.80,1,N,151,239,1,4.5,1.0,0.5,1.26,0.0,0.3,7.56
68,105476838,1,12/13/2017 7:06:10 AM,12/13/2017 7:11:40 AM,1,0.80,1,N,142,230,1,5.5,0.0,0.5,1.00,0.0,0.3,7.30
27,99525452,2,11/24/2017 10:48:13 AM,11/24/2017 10:52:57 AM,1,0.85,1,N,237,161,2,5.5,0.0,0.5,0.00,0.0,0.3,6.30
59,17520716,2,03/03/2017 8:02:59 AM,03/03/2017 8:05:43 AM,1,0.85,1,N,164,170,1,4.5,0.0,0.5,1.59,0.0,0.3,6.89
94,53636202,2,06/23/2017 7:53:53 PM,06/23/2017 8:00:57 PM,2,0.88,1,N,170,234,1,6.5,1.0,0.5,0.50,0.0,0.3,8.80
24,10565287,1,02/13/2017 10:29:33 AM,02/13/2017 10:34:11 AM,1,0.90,1,N,237,237,1,5.5,0.0,0.5,1.25,0.0,0.3,7.55
86,81447972,1,09/28/2017 7:17:44 AM,09/28/2017 7:21:35 AM,1,0.90,1,N,237,162,1,5.0,0.0,0.5,1.00,0.0,0.3,6.80

In [7]:
#==> ENTER YOUR CODE HERE
df.sort_values(by='total_amount').head(20)
# Sort the data by total amount and print the top 20 values

,Unnamed: 0,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount
49,34839590,2,04/27/2017 7:26:57 AM,04/27/2017 7:28:21 AM,1,0.42,1,N,234,107,1,3.5,0.0,0.5,0.86,0.0,0.3,5.16
65,110794327,2,12/31/2017 1:03:12 PM,12/31/2017 1:06:52 PM,6,0.71,1,N,161,229,2,4.5,0.0,0.5,0.00,0.0,0.3,5.30
85,74722231,1,09/06/2017 11:37:10 AM,09/06/2017 11:40:44 AM,1,0.40,1,N,140,140,2,4.5,0.0,0.5,0.00,0.0,0.3,5.30
38,10421657,1,02/12/2017 6:45:41 PM,02/12/2017 6:48:58 PM,4,0.40,1,N,142,143,1,4.0,0.0,0.5,0.72,0.0,0.3,5.52
36,14770087,1,02/24/2017 11:24:50 AM,02/24/2017 11:29:18 AM,1,0.60,1,N,142,142,2,5.0,0.0,0.5,0.00,0.0,0.3,5.80
27,99525452,2,11/24/2017 10:48:13 AM,11/24/2017 10:52:57 AM,1,0.85,1,N,237,161,2,5.5,0.0,0.5,0.00,0.0,0.3,6.30
18,35388828,2,04/10/2017 6:12:58 PM,04/10/2017 6:17:39 PM,2,0.63,1,N,263,262,2,5.0,1.0,0.5,0.00,0.0,0.3,6.80
86,81447972,1,09/28/2017 7:17:44 AM,09/28/2017 7:21:35 AM,1,0.90,1,N,237,162,1,5.0,0.0,0.5,1.00,0.0,0.3,6.80
74,36762559,2,05/01/2017 9:42:27 AM,05/01/2017 9:47:29 AM,1,0.78,1,N,13,231,1,5.0,0.0,0.5,1.00,0.0,0.3,6.80
59,17520716,2,03/03/2017 8:02:59 AM,03/03/2017 8:05:43 AM,1,0.85,1,N,164,170,1,4.5,0.0,0.5,1.59,0.0,0.3,6.89
64,21974063,1,03/17/2017 9:17:05 AM,03/17/2017 9:21:34 AM,1,0.70,1,N,237,236,1,5.0,0.0,0.5,1.15,0.0,0.3,6.95
60,34663272,2,04/26/2017 6:08:41 PM,04/26/2017 6:11:08 PM,5,0.38,1,N,236,236,1,4.0,1.0,0.5,1.16,0.0,0.3,6.96
69,65221014,2,08/01/2017 6:09:45 PM,08/01/2017 6:14:05 PM,1,0.96,1,N,162,162,2,5.5,1.0,0.5,0.00,0.0,0.3,7.30
72,68455717,2,08/13/2017 3:50:10 AM,08/13/2017 3:53:43 AM,2,0.95,1,N,68,246,1,5.0,0.5,0.5,1.00,0.0,0.3,7.30
68,105476838,1,12/13/2017 7:06:10 AM,12/13/2017 7:11:40 AM,1,0.80,1,N,142,230,1,5.5,0.0,0.5,1.00,0.0,0.3,7.30
82,86230381,2,10/13/2017 3:48:39 PM,10/13/2017 3:56:17 PM,1,0.96,1,N,249,234,2,6.5,0.0,0.5,0.00,0.0,0.3,7.30
24,10565287,1,02/13/2017 10:29:33 AM,02/13/2017 10:34:11 AM,1,0.90,1,N,237,237,1,5.5,0.0,0.5,1.25,0.0,0.3,7.55
53,25497357,2,03/28/2017 7:10:03 PM,03/28/2017 7:13:20 PM,1,0.80,1,N,151,239,1,4.5,1.0,0.5,1.26,0.0,0.3,7.56
22,113074702,2,01/06/2017 8:12:07 PM,01/06/2017 8:18:37 PM,1,0.52,1,N,90,249,1,5.5,0.5,0.5,1.00,0.0,0.3,7.80
58,22352969,2,03/18/2017 12:12:18 PM,03/18/2017 12:20:32 PM,1,0.78,1,N,230,50,2,7.0,0.0,0.5,0.00,0.0,0.3,7.80

In [8]:
#==> ENTER YOUR CODE HERE
total_amount_sorted = df.sort_values(
    ['total_amount'], ascending=False)['total_amount']
total_amount_sorted.head(20)
# Sort the data by total amount and print the bottom 20 values

29    111.38
21     96.81
11     72.92
6      59.16
92     54.66
98     42.35
32     41.80
55     40.56
47     39.36
78     39.36
66     34.56
89     32.30
3      27.69
50     26.30
81     23.14
88     23.10
14     22.85
15     22.80
87     21.96
62     21.80
Name: total_amount, dtype: float64

In [9]:
#==> ENTER YOUR CODE HERE
df['payment_type'].value_counts()
# How many of each payment type are represented in the data?

payment_type
1    72
2    28
Name: count, dtype: int64

According to the data dictionary, the payment method was encoded as follows:

1 = Credit card  
2 = Cash  
3 = No charge  
4 = Dispute  
5 = Unknown  
6 = Voided trip

In [10]:
#==> ENTER YOUR CODE HERE
print(df[df['payment_type']==1]['tip_amount'].mean())
# What is the average tip for trips paid for with credit card?

#==> ENTER YOUR CODE HERE
print(df[df['payment_type']==2]['tip_amount'].mean())
# What is the average tip for trips paid for with cash?

3.2675
0.0

In [11]:
#==> ENTER YOUR CODE HERE
df['VendorID'].value_counts()
# How many times is each vendor ID represented in the data?

VendorID
2    62
1    38
Name: count, dtype: int64

In [12]:
#==> ENTER YOUR CODE HERE
df['total_amount'].mean()
# What is the mean total amount for each vendor?

np.float64(18.0009)

In [13]:
#==> ENTER YOUR CODE HERE
print(df.loc[df['VendorID']==1])
# Filter the data for credit card payments only

#==> ENTER YOUR CODE HERE
print(df[df['passenger_count']==1])
# Filter the credit-card-only data for passenger count only

    Unnamed: 0  VendorID    tpep_pickup_datetime   tpep_dropoff_datetime  \
1     35634249         1   04/11/2017 2:53:28 PM   04/11/2017 3:19:58 PM
2    106203690         1   12/15/2017 7:26:56 AM   12/15/2017 7:34:08 AM
9     95294817         1   11/10/2017 3:20:29 PM   11/10/2017 3:40:55 PM
12    46782248         1   06/09/2017 7:00:26 PM   06/09/2017 7:20:11 PM
14    14168279         1   02/22/2017 3:18:31 PM   02/22/2017 3:42:50 PM
16    69088676         1   08/15/2017 7:48:08 PM   08/15/2017 8:00:37 PM
20   110690689         1  12/30/2017 11:52:44 PM  12/30/2017 11:58:57 PM
23    54636365         1  06/27/2017 12:08:22 AM  06/27/2017 12:13:45 AM
24    10565287         1  02/13/2017 10:29:33 AM  02/13/2017 10:34:11 AM
26    93194366         1   11/04/2017 1:27:59 AM   11/04/2017 1:44:05 AM
28    99074251         1  11/22/2017 10:24:17 AM  11/22/2017 10:38:52 AM
30    67540161         1   08/09/2017 9:01:50 PM   08/09/2017 9:14:28 PM
31    35914864         1  04/12/2017 11:07:56 AM  04/12/2017 11:19:29 AM
33    90465096         1   10/26/2017 7:43:07 PM   10/26/2017 8:06:02 PM
34    18173620         1   03/04/2017 6:19:04 PM   03/04/2017 6:32:13 PM
36    14770087         1  02/24/2017 11:24:50 AM  02/24/2017 11:29:18 AM
38    10421657         1   02/12/2017 6:45:41 PM   02/12/2017 6:48:58 PM
41    15086430         1   02/25/2017 7:41:32 AM   02/25/2017 7:50:26 AM
45    68798000         1   08/14/2017 5:15:32 PM   08/14/2017 5:25:28 PM
51    27809467         1   04/04/2017 4:22:03 PM   04/04/2017 4:35:30 PM
52     1361166         1   01/05/2017 2:56:32 PM   01/05/2017 3:24:31 PM
54    73498565         1   09/01/2017 9:37:29 AM  09/01/2017 10:00:14 AM
56     9517173         1  02/10/2017 11:47:00 AM  02/10/2017 12:09:43 PM
64    21974063         1   03/17/2017 9:17:05 AM   03/17/2017 9:21:34 AM
68   105476838         1   12/13/2017 7:06:10 AM   12/13/2017 7:11:40 AM
70    85218699         1   10/10/2017 2:40:11 PM   10/10/2017 2:54:27 PM
76    30892521         1   04/16/2017 2:43:35 AM   04/16/2017 3:04:48 AM
77    15158530         1   02/25/2017 1:04:27 PM   02/25/2017 1:15:41 PM
79     2661149         1   01/10/2017 9:06:58 PM   01/10/2017 9:13:20 PM
84    64344057         1   07/29/2017 1:27:34 PM   07/29/2017 1:36:28 PM
85    74722231         1  09/06/2017 11:37:10 AM  09/06/2017 11:40:44 AM
86    81447972         1   09/28/2017 7:17:44 AM   09/28/2017 7:21:35 AM
88    16215929         1   02/28/2017 6:02:05 PM   02/28/2017 6:13:30 PM
89    16416397         1   03/10/2017 6:31:50 PM   03/10/2017 6:58:46 PM
90    38609090         1   05/06/2017 2:54:22 PM   05/06/2017 3:19:17 PM
92    87475909         1   10/17/2017 2:29:39 PM   10/17/2017 3:00:14 PM
93    10038766         1   02/11/2017 7:09:12 PM   02/11/2017 7:32:20 PM
98    97913057         1   11/18/2017 1:04:54 PM   11/18/2017 1:39:53 PM

    passenger_count  trip_distance  RatecodeID store_and_fwd_flag  \
1                 1            1.8           1                  N
2                 1            1.0           1                  N
9                 1            1.6           1                  N
12                1            3.0           1                  N
14                1            3.3           1                  N
16                1            3.6           1                  N
20                1            1.1           1                  N
23                1            1.7           1                  N
24                1            0.9           1                  N
26                1            2.7           1                  N
28                1            2.3           1                  N
30                1            2.3           1                  N
31                4            1.5           1                  N
33                1            2.9           1                  N
34                1            1.7           1                  N
36                1            0.6           1                  N
38                4            0.4           1                  N
41                1            2.0           1                  N
45                1            1.5           1                  N
51                1            2.2           1                  N
52                2            2.6           1                  N
54                1            2.9           1                  N
56                1            2.7           1                  N
64                1            0.7           1                  N
68                1            0.8           1                  N
70                4            1.9           1                  N
76                3            4.3           1                  N
77                1            1.9           1                  N
79                1            2.0           1                  N
84                1            1.6           1                  N
85                1            0.4           1                  N
86                1            0.9           1                  N
88                1            4.9           1                  N
89                1            9.6           1                  N
90                1            2.9           1                  N
92                1           13.8           1                  N
93                1            1.7           1                  N
98                1           10.0           1                  N

    PULocationID  DOLocationID  payment_type  fare_amount  extra  mta_tax  \
1            186            43             1         16.0    0.0      0.5
2            262           236             1          6.5    0.0      0.5
9            239           237             1         13.0    0.0      0.5
12            13           148             1         15.0    1.0      0.5
14           238           161             1         17.5    0.0      0.5
16           163            41             1         12.5    1.0      0.5
20           166           238             2          6.5    0.5      0.5
23           162           263             1          7.0    0.5      0.5
24           237           237             1          5.5    0.0      0.5
26            50           263             1         13.0    0.5      0.5
28           162           113             1         11.0    0.0      0.5
30           163           234             1         10.5    0.5      0.5
31           239            43             2          9.0    0.0      0.5
33           230           238             1         15.5    1.0      0.5
34           236           161             1         10.5    0.0      0.5
36           142           142             2          5.0    0.0      0.5
38           142           143             1          4.0    0.0      0.5
41           170           113             1          9.0    0.0      0.5
45           239           230             1          8.5    1.0      0.5
51           163            90             2         10.5    1.0      0.5
52           100           237             2         17.5    0.0      0.5
54            24            48             2         16.0    0.0      0.5
56           238           161             1         15.5    0.0      0.5
64           237           236             1          5.0    0.0      0.5
68           142           230             1          5.5    0.0      0.5
70           144            68             2         10.5    0.0      0.5
76           249           255             1         17.5    0.5      0.5
77           107           161             1          9.5    0.0      0.5
79           246            50             2          8.0    0.5      0.5
84           249           186             1          8.0    0.0      0.5
85           140           140             2          4.5    0.0      0.5
86           237           162             1          5.0    0.0      0.5
88            87           170             1         16.0    1.0      0.5
89           234           244             2         30.5    1.0      0.5
90            79           255             2         17.5    0.0      0.5
92           138            51             1         39.0    0.0      0.5
93           249           107             1         14.5    0.0      0.5
98           230           138             1         34.5    0.0      0.5

    tip_amount  tolls_amount  improvement_surcharge  total_amount
1         4.00          0.00                    0.3         20.80
2         1.45          0.00                    0.3          8.75
9         2.75          0.00                    0.3         16.55
12        3.35          0.00                    0.3         20.15
14        4.55          0.00                    0.3         22.85
16        2.85          0.00                    0.3         17.15
20        0.00          0.00                    0.3          7.80
23        2.05          0.00                    0.3         10.35
24        1.25          0.00                    0.3          7.55
26        2.85          0.00                    0.3         17.15
28        2.35          0.00                    0.3         14.15
30        1.77          0.00                    0.3         13.57
31        0.00          0.00                    0.3          9.80
33        3.45          0.00                    0.3         20.75
34        1.70          0.00                    0.3         13.00
36        0.00          0.00                    0.3          5.80
38        0.72          0.00                    0.3          5.52
41        1.95          0.00                    0.3         11.75
45        2.55          0.00                    0.3         12.85
51        0.00          0.00                    0.3         12.30
52        0.00          0.00                    0.3         18.30
54        0.00          0.00                    0.3         16.80
56        4.05          0.00                    0.3         20.35
64        1.15          0.00                    0.3          6.95
68        1.00          0.00                    0.3          7.30
70        0.00          0.00                    0.3         11.30
76        2.22          0.00                    0.3         21.02
77        2.55          0.00                    0.3         12.85
79        0.00          0.00                    0.3          9.30
84        1.00          0.00                    0.3          9.80
85        0.00          0.00                    0.3          5.30
86        1.00          0.00                    0.3          6.80
88        5.30          0.00                    0.3         23.10
89        0.00          0.00                    0.3         32.30
90        0.00          0.00                    0.3         18.30
92        9.10          5.76                    0.3         54.66
93        1.00          0.00                    0.3         16.30
98        7.05          0.00                    0.3         42.35
    Unnamed: 0  VendorID    tpep_pickup_datetime   tpep_dropoff_datetime  \
1     35634249         1   04/11/2017 2:53:28 PM   04/11/2017 3:19:58 PM
2    106203690         1   12/15/2017 7:26:56 AM   12/15/2017 7:34:08 AM
3     38942136         2   05/07/2017 1:17:59 PM   05/07/2017 1:48:14 PM
4     30841670         2  04/15/2017 11:32:20 PM  04/15/2017 11:49:03 PM
6     37660487         2   05/03/2017 7:04:09 PM   05/03/2017 8:03:47 PM
..         ...       ...                     ...                     ...
95    20414683         2   03/26/2017 8:06:55 PM   03/26/2017 8:14:43 PM
96    63683638         2  07/27/2017 10:10:04 AM  07/27/2017 10:23:13 AM
97   105056260         2   12/11/2017 8:04:27 PM   12/11/2017 8:16:10 PM
98    97913057         1   11/18/2017 1:04:54 PM   11/18/2017 1:39:53 PM
99    22572601         2  03/18/2017 11:41:50 PM  03/18/2017 11:49:21 PM

    passenger_count  trip_distance  RatecodeID store_and_fwd_flag  \
1                 1           1.80           1                  N
2                 1           1.00           1                  N
3                 1           3.70           1                  N
4                 1           4.37           1                  N
6                 1          12.83           1                  N
..              ...            ...         ...                ...
95                1           1.46           1                  N
96                1           1.66           1                  N
97                1           1.63           1                  N
98                1          10.00           1                  N
99                1           1.42           1                  N

    PULocationID  DOLocationID  payment_type  fare_amount  extra  mta_tax  \
1            186            43             1         16.0    0.0      0.5
2            262           236             1          6.5    0.0      0.5
3            188            97             1         20.5    0.0      0.5
4              4           112             2         16.5    0.5      0.5
6             79           241             1         47.5    1.0      0.5
..           ...           ...           ...          ...    ...      ...
95           186           233             1          7.0    0.5      0.5
96           163           100             1         10.0    0.0      0.5
97           161           234             1          9.5    0.5      0.5
98           230           138             1         34.5    0.0      0.5
99           113            68             2          7.0    0.5      0.5

    tip_amount  tolls_amount  improvement_surcharge  total_amount
1         4.00           0.0                    0.3         20.80
2         1.45           0.0                    0.3          8.75
3         6.39           0.0                    0.3         27.69
4         0.00           0.0                    0.3         17.80
6         9.86           0.0                    0.3         59.16
..         ...           ...                    ...           ...
95        1.24           0.0                    0.3          9.54
96        1.20           0.0                    0.3         12.00
97        2.16           0.0                    0.3         12.96
98        7.05           0.0                    0.3         42.35
99        0.00           0.0                    0.3          8.30

[68 rows x 18 columns]

In [14]:
#==> ENTER YOUR CODE HERE
df.loc[df['payment_type']==1].groupby('passenger_count')['tip_amount'].mean()
# Calculate the average tip amount for each passenger count (credit card payments only)

passenger_count
1    3.372549
2    3.342727
3    3.273333
4    2.913333
5    1.160000
6    2.256667
Name: tip_amount, dtype: float64