# 07 · Adding & Removing Rows/Columns

Pandas' equivalents of `ALTER TABLE ... ADD/DROP COLUMN`, `INSERT INTO`, and `DELETE FROM`.

In [2]:
import pandas as pd

people = {
    'first': ['Corey', 'Jane', 'John'],
    'last': ['Schafer', 'Doe', 'Doe'],
    'email': ['CoreyMSchafer@gmail.com', 'JaneDoe@email.com', 'JohnDoe@email.com']
}
df = pd.DataFrame(people)

In [3]:
df['fullname'] = df['first'] + " " + df['last']
df
# SQL: SELECT *, CONCAT(first, ' ', last) AS fullname FROM people;
# to persist it as a real column:
# ALTER TABLE people ADD COLUMN fullname TEXT;
# UPDATE people SET fullname = CONCAT(first, ' ', last);

   first     last                    email       fullname
0  Corey  Schafer  CoreyMSchafer@gmail.com  Corey Schafer
1   Jane      Doe        JaneDoe@email.com       Jane Doe
2   John      Doe        JohnDoe@email.com       John Doe

In [4]:
df.drop(columns=['first', 'last'], inplace=True)
df
# SQL: ALTER TABLE people DROP COLUMN first;
#      ALTER TABLE people DROP COLUMN last;

                     email       fullname
0  CoreyMSchafer@gmail.com  Corey Schafer
1        JaneDoe@email.com       Jane Doe
2        JohnDoe@email.com       John Doe

In [5]:
df['fullname'].str.split(' ', expand=True)   # preview — splits into separate columns, not saved yet
# SQL: SELECT SUBSTRING_INDEX(fullname, ' ', 1) AS first,
#             SUBSTRING_INDEX(fullname, ' ', -1) AS last
#      FROM people;

       0        1
0  Corey  Schafer
1   Jane      Doe
2   John      Doe

In [6]:
df[['first', 'last']] = df['fullname'].str.split(' ', expand=True)
df
# SQL: ALTER TABLE people ADD COLUMN first TEXT, ADD COLUMN last TEXT;
#      UPDATE people SET first = SUBSTRING_INDEX(fullname, ' ', 1),
#                         last  = SUBSTRING_INDEX(fullname, ' ', -1);

                     email       fullname  first     last
0  CoreyMSchafer@gmail.com  Corey Schafer  Corey  Schafer
1        JaneDoe@email.com       Jane Doe   Jane      Doe
2        JohnDoe@email.com       John Doe   John      Doe

In [7]:
df = pd.concat([df, pd.DataFrame([{'first': 'Tony'}])], ignore_index=True)
df
# SQL: INSERT INTO people (first) VALUES ('Tony');

                     email       fullname  first     last
0  CoreyMSchafer@gmail.com  Corey Schafer  Corey  Schafer
1        JaneDoe@email.com       Jane Doe   Jane      Doe
2        JohnDoe@email.com       John Doe   John      Doe
3                      NaN            NaN   Tony      NaN

In [8]:
df.drop(index=3, inplace=True)
df
# SQL: DELETE FROM people WHERE id = 3;

                     email       fullname  first     last
0  CoreyMSchafer@gmail.com  Corey Schafer  Corey  Schafer
1        JaneDoe@email.com       Jane Doe   Jane      Doe
2        JohnDoe@email.com       John Doe   John      Doe

In [9]:
filt = df['last'] == 'Schafer'
df.drop(index=df[filt].index, inplace=True)
df
# SQL: DELETE FROM people WHERE last = 'Schafer';

               email  fullname first last
1  JaneDoe@email.com  Jane Doe  Jane  Doe
2  JohnDoe@email.com  John Doe  John  Doe

In [15]:
data = {
  'street': [
    '5230 Newell Road',
    '1381 9th Avenue',
    '1709 Broderick St',
    '2640 Steiner St',
    '2601 Lyon St',
    '1600 Amphitheatre Parkway',
    '7500 N Glenoaks Boulevard',
    '4501 Glencoe Avenue',
    '232 Santa Margarita Ave',
    '471 Emerson Street'
  ],
  'city': [
    'Palo Alto',
    'San Francisco',
    'San Francisco',
    'San Francisco',
    'San Francisco',
    'Mountain View',
    'Burbank',
    'Marina del Rey',
    'Menlo Park',
    None
  ],
  'state': [
    'CA',
    'CA',
    'CA',
    'CA',
    'CA',
    'CA',
    'CA',
    'CA',
    None,
    None
  ],
  'zip_code': [
    94303,
    94122,
    94115,
    94123,
    94123,
    94043,
    91504,
    90292,
    94025,
    None
  ],
  'delivery_type': [
    'First Class',
    'Standard',
    'Priority',
    'Standard',
    None,
    'Expresss',
    'Standard',
    'Standard',
    None,
    None
  ]
}

df = pd.DataFrame(data)

In [16]:
cleaned_df = df.dropna()
cleaned_df

                      street            city state  zip_code delivery_type
0           5230 Newell Road       Palo Alto    CA   94303.0   First Class
1            1381 9th Avenue   San Francisco    CA   94122.0      Standard
2          1709 Broderick St   San Francisco    CA   94115.0      Priority
3            2640 Steiner St   San Francisco    CA   94123.0      Standard
5  1600 Amphitheatre Parkway   Mountain View    CA   94043.0      Expresss
6  7500 N Glenoaks Boulevard         Burbank    CA   91504.0      Standard
7        4501 Glencoe Avenue  Marina del Rey    CA   90292.0      Standard

In [17]:
# if we only care about missing values in specific columns
cleaned_df = df.dropna(subset = ['state', 'city'])
cleaned_df

                      street            city state  zip_code delivery_type
0           5230 Newell Road       Palo Alto    CA   94303.0   First Class
1            1381 9th Avenue   San Francisco    CA   94122.0      Standard
2          1709 Broderick St   San Francisco    CA   94115.0      Priority
3            2640 Steiner St   San Francisco    CA   94123.0      Standard
4               2601 Lyon St   San Francisco    CA   94123.0           NaN
5  1600 Amphitheatre Parkway   Mountain View    CA   94043.0      Expresss
6  7500 N Glenoaks Boulevard         Burbank    CA   91504.0      Standard
7        4501 Glencoe Avenue  Marina del Rey    CA   90292.0      Standard

In [18]:
# The following code would fill in the missing values for the location column
df['delivery_type'] = df['delivery_type'].fillna('Standard')    #4
df

                      street            city state  zip_code delivery_type
0           5230 Newell Road       Palo Alto    CA   94303.0   First Class
1            1381 9th Avenue   San Francisco    CA   94122.0      Standard
2          1709 Broderick St   San Francisco    CA   94115.0      Priority
3            2640 Steiner St   San Francisco    CA   94123.0      Standard
4               2601 Lyon St   San Francisco    CA   94123.0      Standard
5  1600 Amphitheatre Parkway   Mountain View    CA   94043.0      Expresss
6  7500 N Glenoaks Boulevard         Burbank    CA   91504.0      Standard
7        4501 Glencoe Avenue  Marina del Rey    CA   90292.0      Standard
8    232 Santa Margarita Ave      Menlo Park   NaN   94025.0      Standard
9         471 Emerson Street             NaN   NaN       NaN      Standard

In [ ]:
# Finally, assuming the data is numerical, we can fill empty values with the average using .mean().
mean_zip_code = df['zip_code'].mean()

df['zip_code'] = df['zip_code'].fillna(mean_zip_code)

In [20]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
9    False
dtype: bool

In [21]:
df[df.duplicated()]

Empty DataFrame
Columns: [street, city, state, zip_code, delivery_type]
Index: []

In [22]:
# .drop_duplicates(). This will remove all rows that are exactly identical to another row in the DataFrame:
no_dupes = df.drop_duplicates()