In [9]:
import pandas as pd

data = {
  'street': [
    '5230 Newell Road',
    '1381 9th Avenue',
    '1709 Broderick St',
    '2640 Steiner St',
    '2601 Lyon St',
    '1600 Amphitheatre Parkway',
    '7500 N Glenoaks Boulevard',
    '4501 Glencoe Avenue',
    '232 Santa Margarita Ave',
    '471 Emerson Street',
    '471 Emerson Street'
  ],
  'city': [
    'Palo Alto',
    'San Francisco',
    'San Francisco',
    'San Francisco',
    'San Francisco',
    'Mountain View',
    'Burbank',
    'Marina del Rey',
    'Menlo Park',
    None,
    None
  ],
  'state': [
    'CA',
    'CA',
    'CA',
    'CA',
    'CA',
    'CA',
    'CA',
    'CA',
    None,
    None,
    None
  ],
  'zip_code': [
    94303,
    94122,
    94115,
    94123,
    94123,
    94043,
    91504,
    90292,
    94025,
    None,
    None
  ],
  'delivery_type': [
    'First Class',
    'Standard',
    'Priority',
    'Standard',
    None,
    'Expresss',
    'Standard',
    'Standard',
    None,
    None,
    None
  ]
}

df = pd.DataFrame(data)
df

                       street            city state  zip_code delivery_type
0            5230 Newell Road       Palo Alto    CA   94303.0   First Class
1             1381 9th Avenue   San Francisco    CA   94122.0      Standard
2           1709 Broderick St   San Francisco    CA   94115.0      Priority
3             2640 Steiner St   San Francisco    CA   94123.0      Standard
4                2601 Lyon St   San Francisco    CA   94123.0           NaN
5   1600 Amphitheatre Parkway   Mountain View    CA   94043.0      Expresss
6   7500 N Glenoaks Boulevard         Burbank    CA   91504.0      Standard
7         4501 Glencoe Avenue  Marina del Rey    CA   90292.0      Standard
8     232 Santa Margarita Ave      Menlo Park   NaN   94025.0           NaN
9          471 Emerson Street             NaN   NaN       NaN           NaN
10         471 Emerson Street             NaN   NaN       NaN           NaN

In [10]:
cleaned_df = df.dropna()
cleaned_df

                      street            city state  zip_code delivery_type
0           5230 Newell Road       Palo Alto    CA   94303.0   First Class
1            1381 9th Avenue   San Francisco    CA   94122.0      Standard
2          1709 Broderick St   San Francisco    CA   94115.0      Priority
3            2640 Steiner St   San Francisco    CA   94123.0      Standard
5  1600 Amphitheatre Parkway   Mountain View    CA   94043.0      Expresss
6  7500 N Glenoaks Boulevard         Burbank    CA   91504.0      Standard
7        4501 Glencoe Avenue  Marina del Rey    CA   90292.0      Standard

In [11]:
# if we only care about missing values in specific columns
cleaned_df = df.dropna(subset = ['state', 'city'])
cleaned_df

                      street            city state  zip_code delivery_type
0           5230 Newell Road       Palo Alto    CA   94303.0   First Class
1            1381 9th Avenue   San Francisco    CA   94122.0      Standard
2          1709 Broderick St   San Francisco    CA   94115.0      Priority
3            2640 Steiner St   San Francisco    CA   94123.0      Standard
4               2601 Lyon St   San Francisco    CA   94123.0           NaN
5  1600 Amphitheatre Parkway   Mountain View    CA   94043.0      Expresss
6  7500 N Glenoaks Boulevard         Burbank    CA   91504.0      Standard
7        4501 Glencoe Avenue  Marina del Rey    CA   90292.0      Standard

In [12]:
# The following code would fill in the missing values for the location column
df['delivery_type'] = df['delivery_type'].fillna('Standard')    #4
df

                       street            city state  zip_code delivery_type
0            5230 Newell Road       Palo Alto    CA   94303.0   First Class
1             1381 9th Avenue   San Francisco    CA   94122.0      Standard
2           1709 Broderick St   San Francisco    CA   94115.0      Priority
3             2640 Steiner St   San Francisco    CA   94123.0      Standard
4                2601 Lyon St   San Francisco    CA   94123.0      Standard
5   1600 Amphitheatre Parkway   Mountain View    CA   94043.0      Expresss
6   7500 N Glenoaks Boulevard         Burbank    CA   91504.0      Standard
7         4501 Glencoe Avenue  Marina del Rey    CA   90292.0      Standard
8     232 Santa Margarita Ave      Menlo Park   NaN   94025.0      Standard
9          471 Emerson Street             NaN   NaN       NaN      Standard
10         471 Emerson Street             NaN   NaN       NaN      Standard

In [13]:
# Finally, assuming the data is numerical, we can fill empty values with the average using .mean().
mean_zip_code = df['zip_code'].mean()

df['zip_code'] = df['zip_code'].fillna(mean_zip_code        )

In [14]:
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
dtype: bool

In [19]:
df[df.duplicated()]

                street city state      zip_code delivery_type
10  471 Emerson Street  NaN   NaN  93405.555556      Standard

In [20]:
# .drop_duplicates(). This will remove all rows that are exactly identical to another row in the DataFrame:
no_dupes = df.drop_duplicates()
no_dupes

                      street            city state      zip_code delivery_type
0           5230 Newell Road       Palo Alto    CA  94303.000000   First Class
1            1381 9th Avenue   San Francisco    CA  94122.000000      Standard
2          1709 Broderick St   San Francisco    CA  94115.000000      Priority
3            2640 Steiner St   San Francisco    CA  94123.000000      Standard
4               2601 Lyon St   San Francisco    CA  94123.000000      Standard
5  1600 Amphitheatre Parkway   Mountain View    CA  94043.000000      Expresss
6  7500 N Glenoaks Boulevard         Burbank    CA  91504.000000      Standard
7        4501 Glencoe Avenue  Marina del Rey    CA  90292.000000      Standard
8    232 Santa Margarita Ave      Menlo Park   NaN  94025.000000      Standard
9         471 Emerson Street             NaN   NaN  93405.555556      Standard

In [21]:
# Removes rows that have a duplicate city with another row
unique_city = df.drop_duplicates(subset = ['city'])
unique_city

                      street            city state      zip_code delivery_type
0           5230 Newell Road       Palo Alto    CA  94303.000000   First Class
1            1381 9th Avenue   San Francisco    CA  94122.000000      Standard
5  1600 Amphitheatre Parkway   Mountain View    CA  94043.000000      Expresss
6  7500 N Glenoaks Boulevard         Burbank    CA  91504.000000      Standard
7        4501 Glencoe Avenue  Marina del Rey    CA  90292.000000      Standard
8    232 Santa Margarita Ave      Menlo Park   NaN  94025.000000      Standard
9         471 Emerson Street             NaN   NaN  93405.555556      Standard